### ISSUE TITLE
Any Windows versions of Arc_plot in the near Future

### ISSUE THREAD

**Issue by Drhicom** [smartbitcoin/arc_plot#3]
Do you plan any Windows versions in the near Future of Arc_plot??

**Comment by Motophan** [comment]
https://github.com/smartbitcoin/arc_plot/issues/4

If this gets implemented you could run this with little modifications using cygwin

You can also run this right now with wsl, but as the above referenced issue you are pretty much forced to do it on ubuntu 22.xx wsl base because the binary ships w/o statically linked libraries. 

Both would be solved if the dev could compile this with a gcc flag. 
Re: dev, please reconsider.

**Comment by smartbitcoin** [comment]
as compression format undergoing ,  all plan was paused for porting
